name: 'Photon Image Runner'
description: 'Action to modify an os image, targeted at coprocessor images for PhotonVision'

inputs:
  image_url:
    description: 'The url for the base image. If it is a local file, provide the file path'
    required: true
    default: ''
  additional_mb:
    description: 'Amount (in MB) to increase the size of the image'
    required: false
    default: 0
  minimum_free_mb:
    description: 'Amount (in MB) of free space that should be available for commands'
    required: false
    default: 0
  commands:
    description: 'The commands to run in the image'
    required: true
    default: 'echo "No commands provided"'
  boot_partition:
    description: 'Partition number for boot, will be mounted at /boot'
    required: false
    default: '1'
  root_location:
    description: 'Location of the root as either "partition=X" or "offset=XXX"'
    required: false
    default: 'partition=2'
  shrink_image:
    description: 'Make the output image file as small as possible'
    required: false
    default: 'yes'

outputs:
  image:
    description: 'Path to modified image'
    value: ${{ steps.get_image.outputs.image }}

runs:
  using: 'composite'
  steps:
    - name: Get base image
      run: |
          sudo --preserve-env bash ${GITHUB_ACTION_PATH}/get_image.sh ${{ inputs.image_url }}
      shell: bash
      id: get_image

    - name: Mount image
      run: |
          sudo --preserve-env bash "${GITHUB_ACTION_PATH}/mount_image.sh" "${{ steps.get_image.outputs.image }}" "${{ inputs.additional_mb }}" "${{ inputs.minimum_free_mb }}" "${{ inputs.root_location }}" "${{ inputs.boot_partition }}"
      shell: bash
      id: mount_image

    - name: Run commands
      run: |
          echo "Running the commands"
          chroot_scriptdir=/tmp/build
          scriptdir="${{ env.rootdir }}${chroot_scriptdir}"
          sudo mkdir --parents "${scriptdir}"
          sudo mount --bind "${{ github.workspace }}" "${scriptdir}"

          cat >> "${scriptdir}/commands.sh" << EOF
          #!/bin/bash
          # set -exo pipefail
          # export SHELLOPTS
          # export BASHOPTS
          cd "${chroot_scriptdir}"
          ${{ inputs.commands }}
          EOF

          sudo chmod +x "${scriptdir}/commands.sh"
          sudo --preserve-env chroot "${{ env.rootdir }}" bash -c "${chroot_scriptdir}/commands.sh"
      shell: bash
      id: run_commands

    - name: Clean up and pack image
      run: |
          sudo --preserve-env bash ${GITHUB_ACTION_PATH}/pack_image.sh "${{ steps.get_image.outputs.image }}" "${{ inputs.shrink_image }}"
      shell: bash
      id: pack_image
